### ISSUE TITLE
HTTPS support?

### ISSUE THREAD

**Issue by Ambient-Impact** [LeaVerou/duoload#2]
I love how simple and effective this is, but I'm wondering if you're planning on supporting HTTPS sites? As it is, I can load the default sites provided, and http://example.com, but whenever I try to load any site that is only accessible via HTTPS (like [my own site](https://ambientimpact.com), or [mozilla.org](https://www.mozilla.org)), I just get a blank frame. I'm using Firefox Developer Edition 53.0a2 (2017-02-07) (32-bit) with the tracking protection Test Pilot addon disabled for your site, and uBlock Origin also disabled on your site, but those seem to have made no difference. Maybe this is security thing?

**Comment by Ambient-Impact** [comment]
Update: Chrome 57.0.2987.21 beta (64-bit) does the same thing, but Edge 38.14393.0.0 actually gives me a reason (while still not showing me the frame contents):
![duoload](https://cloud.githubusercontent.com/assets/2289006/22763162/0ed7fe04-ee31-11e6-890a-ff32b5b112dc.png)

I wonder if this is unfixable, or if there is some way around this?

**Comment by felansu** [comment]
@Ambient-Impact, please read http://stackoverflow.com/search?q=https+iframe

**Comment by LeaVerou** [comment]
It loads https just fine, for example try changing the lea.verou.me URL to https.
The reason duoload itself doesn't use https is so that it can be used to test both http and https sites.
As the error message in your screenshot is saying, "the publisher doesn't allow it to be displayed in an iframe" = X-Frame-Options is in effect. There's no way around this, duoload just can't be used for sites with that header.

**Comment by Ambient-Impact** [comment]
My bad, thanks for the info!
